version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "training"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin123123"
    ports:
      - "5432:5432"
