services:
  nuxt:
    build: ./app
    container_name: nuxt
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - api

  api:
    build: ./api
    container_name: api
    ports:
      - ${APP_PORT:-8000}:${APP_PORT:-8000}
      - ${WS_PORT:-8030}:${WS_PORT:-8030}
    env_file:
      - ./.env
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - postgres
      - s3

  s3:
    image: minio/minio:latest
    container_name: s3
    ports:
      - ${S3_PORT:-9000}:${S3_PORT:-9000}
      - 8900:8900
    environment:
      - MINIO_ROOT_USER=${S3_USER}
      - MINIO_ROOT_PASSWORD=${S3_PASSWORD}
    command: minio server /data/minio --console-address ":8900"
    volumes:
      - s3:/data/minio
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
       - POSTGRES_DB=${DB_NAME}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:
  s3:

networks:
  app-network:
    driver: bridge
