version: "3.9"
services:
  api:
    build: ./backend
    container_name: "node-api"
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    env_file:
      - ./.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
       - POSTGRES_DB=${DB_NAME}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

