version: "3.9"
services:
  api:
    build: ./backend
    container_name: "node-api"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: "training"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin123123"
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

